plex_download: https://downloads.plex.tv/plex-media-server/0.9.12.4.1192-9a47d21/plexmediaserver_0.9.12.4.1192-9a47d21_amd64.deb
plex_deb_path: /tmp/plex.deb
plex_application_support_dir: "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server"
app_store_repo: "git://github.com/mikedm139/UnSupportedAppstore.bundle.git"